export const ADMIN_PATH = '/admin'
export const LOGIN_PATH = '/login'
export const REGISTRATION_PATH = '/registration'
export const CLIENT_PATH = '/user'
export const TOURS_PATH = '/tours'
export const TOUR_PATH = '/tour/:id'
export const SERVICEP_PATH = '/servicep'